/**
 * One-shot generator: supabase/seed/admin-config-export.json → seed_hash_pku_wc2026.sql
 * Run: node supabase/seed/generate-seed.js
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '../..');
const exportPath = path.join(__dirname, 'admin-config-export.json');
const outPath = path.join(__dirname, 'seed_hash_pku_wc2026.sql');

const participants = [
  { name: 'Davin', avatar: 'QIU.png', color: '#3498db', order: 1, goal: 71 },
  { name: 'Ndod', avatar: 'NDO.jpeg', color: '#2ecc71', order: 2, goal: 82 },
  { name: 'Khuang', avatar: 'KHU.png', color: '#f1c40f', order: 3, goal: 88 },
  { name: 'Marten', avatar: 'MAR.jpg', color: '#9b59b6', order: 4, goal: 57 },
  { name: 'Cham', avatar: 'CHA.jpg', color: '#e74c3c', order: 5, goal: 117 },
  { name: 'Willy', avatar: 'WIL.png', color: '#e67e22', order: 6, goal: 81 },
  { name: 'Wesly', avatar: 'WES.jpg', color: '#00bcd4', order: 7, goal: 93 },
];

const teamSupporters = {
  Portugal: ['Davin'],
  Argentina: ['Davin', 'Ndod', 'Khuang', 'Marten', 'Cham', 'Willy'],
  'United States': ['Davin'],
  Colombia: ['Davin', 'Khuang', 'Marten', 'Cham'],
  Norway: ['Davin', 'Ndod', 'Khuang', 'Marten', 'Cham', 'Willy'],
  Canada: ['Davin', 'Khuang'],
  Algeria: ['Davin', 'Khuang'],
  'DR Congo': ['Davin', 'Ndod'],
  France: ['Ndod', 'Cham', 'Willy'],
  Morocco: ['Ndod', 'Cham', 'Wesly'],
  Croatia: ['Ndod'],
  Senegal: ['Ndod', 'Marten', 'Cham', 'Willy', 'Wesly'],
  'South Africa': ['Ndod', 'Willy'],
  Spain: ['Khuang', 'Marten', 'Wesly'],
  Belgium: ['Khuang', 'Willy'],
  'Bosnia and Herzegovina': ['Khuang', 'Wesly'],
  Japan: ['Marten', 'Willy', 'Wesly'],
  Ghana: ['Marten', 'Cham'],
  Austria: ['Marten', 'Cham'],
  'Cape Verde': ['Willy'],
  Brazil: ['Wesly'],
  Sweden: ['Wesly'],
  Paraguay: ['Wesly'],
};

const sideQuest = {
  champion: {
    Argentina: { flag: 'ar', supporters: ['Khuang', 'Willy'] },
    Portugal: { flag: 'pt', supporters: ['Davin'] },
    France: { flag: 'fr', supporters: ['Ndod', 'Cham'] },
    Spain: { flag: 'es', supporters: ['Marten'] },
    Brazil: { flag: 'br', supporters: ['Wesly'] },
  },
  runnerup: {
    Argentina: { flag: 'ar', supporters: ['Cham', 'Davin', 'Ndod', 'Marten'] },
    Spain: { flag: 'es', supporters: ['Khuang', 'Wesly'] },
    France: { flag: 'fr', supporters: ['Willy'] },
  },
  third: {
    Brazil: { flag: 'br', supporters: ['Davin', 'Marten'] },
    Spain: { flag: 'es', supporters: ['Ndod'] },
    France: { flag: 'fr', supporters: ['Khuang', 'Wesly'] },
    Portugal: { flag: 'pt', supporters: ['Cham', 'Willy'] },
  },
};

function sqlStr(s) {
  if (s === null || s === undefined) return 'null';
  return "'" + String(s).replace(/'/g, "''") + "'";
}

function sqlArr(arr) {
  if (!arr || !arr.length) return "'{}'::text[]";
  return 'array[' + arr.map(sqlStr).join(', ') + ']::text[]';
}

function sqlJson(obj) {
  if (obj === null || obj === undefined) return 'null';
  return sqlStr(JSON.stringify(obj)) + '::jsonb';
}

const LABEL_ROUND_MAP = [
  ['Perebutan Juara 3', 'Third Place'],
  ['Semifinal', 'Semi-final'],
  ['Perempat Final', 'Quarter-final'],
  ['16 Besar', 'R16'],
  ['Grup', 'Group'],
];

function translateText(s) {
  let out = String(s || '');
  const countryPairs = [
    ['Afrika Selatan', 'South Africa'], ['Amerika Serikat', 'United States'],
    ['Bosnia-Herzegovina', 'Bosnia and Herzegovina'], ['Pantai Gading', 'Ivory Coast'],
    ['Tanjung Verde', 'Cape Verde'], ['RD Kongo', 'DR Congo'], ['Belanda', 'Netherlands'],
    ['Maroko', 'Morocco'], ['Jerman', 'Germany'], ['Prancis', 'France'], ['Swedia', 'Sweden'],
    ['Belgia', 'Belgium'], ['Spanyol', 'Spain'], ['Kroasia', 'Croatia'], ['Brasil', 'Brazil'],
    ['Jepang', 'Japan'], ['Norwegia', 'Norway'], ['Meksiko', 'Mexico'], ['Ekuador', 'Ecuador'],
    ['Inggris', 'England'], ['Aljazair', 'Algeria'], ['Kolombia', 'Colombia'], ['Mesir', 'Egypt'],
    ['Kanada', 'Canada'],
  ];
  for (const [from, to] of countryPairs) out = out.split(from).join(to);
  for (const [from, to] of LABEL_ROUND_MAP) out = out.split(from).join(to);
  return out
    .replace(/\u00e2\u0080\u0094/g, '—')
    .replace(/â\s*[\u0080-\u009f]?\s*"/g, '—')
    .replace(/\sâ\s*[\u0080-\u009f]?\s*/g, ' — ')
    .replace(/\bJuli\b/g, 'July')
    .replace(/\bJuni\b/g, 'June');
}

const config = JSON.parse(fs.readFileSync(exportPath, 'utf8'));
config.lastUpdated = translateText(config.lastUpdated);
(config.finishedMatches || []).forEach(m => {
  if (m.label) m.label = translateText(m.label);
});

const lines = [];
lines.push('-- Seed HASH PKU / WC 2026 — jalankan SETELAH 20260720_init_schema.sql');
lines.push('-- Generated by generate-seed.js');
lines.push('');
lines.push('begin;');
lines.push('');
lines.push(`insert into public.communities (slug, name, settings)`);
lines.push(`values ('hash-pku', 'HASH PKU', '{}'::jsonb)`);
lines.push(`on conflict (slug) do update set name = excluded.name;`);
lines.push('');
lines.push(`insert into public.leagues (community_id, slug, title, year, timezone, last_updated)`);
lines.push(`select c.id, 'wc-2026', 'Arisan World Cup 2026', 2026, 'Asia/Jakarta', ${sqlStr(config.lastUpdated)}`);
lines.push(`from public.communities c where c.slug = 'hash-pku'`);
lines.push(`on conflict (community_id, slug) do update set`);
lines.push(`  title = excluded.title,`);
lines.push(`  year = excluded.year,`);
lines.push(`  last_updated = excluded.last_updated;`);
lines.push('');
lines.push(`-- Clear dependent rows for re-seed`);
lines.push(`delete from public.team_supporters where team_id in (`);
lines.push(`  select t.id from public.teams t`);
lines.push(`  join public.leagues l on l.id = t.league_id`);
lines.push(`  join public.communities c on c.id = l.community_id`);
lines.push(`  where c.slug = 'hash-pku' and l.slug = 'wc-2026'`);
lines.push(`);`);
lines.push(`delete from public.teams where league_id in (`);
lines.push(`  select l.id from public.leagues l join public.communities c on c.id = l.community_id`);
lines.push(`  where c.slug = 'hash-pku' and l.slug = 'wc-2026'`);
lines.push(`);`);
lines.push(`delete from public.participants where league_id in (`);
lines.push(`  select l.id from public.leagues l join public.communities c on c.id = l.community_id`);
lines.push(`  where c.slug = 'hash-pku' and l.slug = 'wc-2026'`);
lines.push(`);`);
lines.push(`delete from public.matches where league_id in (`);
lines.push(`  select l.id from public.leagues l join public.communities c on c.id = l.community_id`);
lines.push(`  where c.slug = 'hash-pku' and l.slug = 'wc-2026'`);
lines.push(`);`);
lines.push(`delete from public.awards where league_id in (`);
lines.push(`  select l.id from public.leagues l join public.communities c on c.id = l.community_id`);
lines.push(`  where c.slug = 'hash-pku' and l.slug = 'wc-2026'`);
lines.push(`);`);
lines.push(`delete from public.side_quests where league_id in (`);
lines.push(`  select l.id from public.leagues l join public.communities c on c.id = l.community_id`);
lines.push(`  where c.slug = 'hash-pku' and l.slug = 'wc-2026'`);
lines.push(`);`);
lines.push('');

for (const p of participants) {
  lines.push(`insert into public.participants (league_id, name, avatar_path, color, sort_order, total_goal_prediction)`);
  lines.push(`select l.id, ${sqlStr(p.name)}, ${sqlStr(p.avatar)}, ${sqlStr(p.color)}, ${p.order}, ${p.goal}`);
  lines.push(`from public.leagues l join public.communities c on c.id = l.community_id`);
  lines.push(`where c.slug = 'hash-pku' and l.slug = 'wc-2026';`);
  lines.push('');
}

const teamNames = Object.keys(teamSupporters);
for (const name of teamNames) {
  lines.push(`insert into public.teams (league_id, name)`);
  lines.push(`select l.id, ${sqlStr(name)}`);
  lines.push(`from public.leagues l join public.communities c on c.id = l.community_id`);
  lines.push(`where c.slug = 'hash-pku' and l.slug = 'wc-2026';`);
  lines.push('');
}

for (const [team, fans] of Object.entries(teamSupporters)) {
  for (const fan of fans) {
    lines.push(`insert into public.team_supporters (team_id, participant_id)`);
    lines.push(`select t.id, p.id`);
    lines.push(`from public.teams t`);
    lines.push(`join public.leagues l on l.id = t.league_id`);
    lines.push(`join public.communities c on c.id = l.community_id`);
    lines.push(`join public.participants p on p.league_id = l.id and p.name = ${sqlStr(fan)}`);
    lines.push(`where c.slug = 'hash-pku' and l.slug = 'wc-2026' and t.name = ${sqlStr(team)};`);
    lines.push('');
  }
}

for (const m of config.finishedMatches || []) {
  lines.push(`insert into public.matches (league_id, match_key, label, status, scores, winner)`);
  lines.push(`select l.id, ${sqlStr(m.id)}, ${sqlStr(m.label || null)}, ${sqlStr(m.status || null)}, ${sqlJson(m.scores)}, ${m.winner === 0 || m.winner === 1 ? m.winner : 'null'}`);
  lines.push(`from public.leagues l join public.communities c on c.id = l.community_id`);
  lines.push(`where c.slug = 'hash-pku' and l.slug = 'wc-2026';`);
  lines.push('');
}

function rewriteImg(url) {
  if (!url) return url;
  // Point local github assets to community-relative paths stored as filenames
  const m = url.match(/assets\/([^?]+)/);
  if (m && url.includes('arisan-wc-2026-knockout-hash-pku')) {
    return decodeURIComponent(m[1]);
  }
  return url;
}

(config.goldenBoot || []).forEach((a, i) => {
  lines.push(`insert into public.awards (league_id, kind, rank, player_name, img, goals, eliminated, winner, supporters)`);
  lines.push(`select l.id, 'golden_boot', ${i}, ${sqlStr(a.name)}, ${sqlStr(rewriteImg(a.img))}, ${a.goals ?? 'null'}, ${!!a.eliminated}, ${!!a.winner}, ${sqlArr(a.supporters)}`);
  lines.push(`from public.leagues l join public.communities c on c.id = l.community_id`);
  lines.push(`where c.slug = 'hash-pku' and l.slug = 'wc-2026';`);
  lines.push('');
});

(config.goldenGlove || []).forEach((a, i) => {
  lines.push(`insert into public.awards (league_id, kind, rank, player_name, img, goals, eliminated, winner, supporters)`);
  lines.push(`select l.id, 'golden_glove', ${i}, ${sqlStr(a.name)}, ${sqlStr(rewriteImg(a.img))}, ${a.goals ?? 'null'}, ${!!a.eliminated}, ${!!a.winner}, ${sqlArr(a.supporters)}`);
  lines.push(`from public.leagues l join public.communities c on c.id = l.community_id`);
  lines.push(`where c.slug = 'hash-pku' and l.slug = 'wc-2026';`);
  lines.push('');
});

for (const [place, teams] of Object.entries(sideQuest)) {
  for (const [teamName, meta] of Object.entries(teams)) {
    lines.push(`insert into public.side_quests (league_id, place, team_name, flag, eliminated, supporters)`);
    lines.push(`select l.id, ${sqlStr(place)}, ${sqlStr(teamName)}, ${sqlStr(meta.flag)}, false, ${sqlArr(meta.supporters)}`);
    lines.push(`from public.leagues l join public.communities c on c.id = l.community_id`);
    lines.push(`where c.slug = 'hash-pku' and l.slug = 'wc-2026';`);
    lines.push('');
  }
}

lines.push('commit;');
lines.push('');

fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
console.log('Wrote', outPath, 'lines:', lines.length);
